const WS_PROTOCOL = 'ws';
const WS_IP = 'localhost';
const WS_PORT = 8091;
const WS_URI = 'im';
//signal
const CONNECT = 'CONNECT';
const DISCONNECT = 'DISCONNECT';
const CONNECT_ACK = 'CONNECT_ACK';
const PUBLISH_PRIVATE = 'PUBLISH_PRIVATE';
const GET_MESSAGES = 'GET_MESSAGES';
export default {
  WS_PROTOCOL,
  WS_IP,
  WS_PORT,
  WS_URI,
  CONNECT,
  DISCONNECT,
  CONNECT_ACK,
  PUBLISH_PRIVATE,
  GET_MESSAGES
}
