const WS_PROTOCOL = 'ws';
//const WS_IP = '192.1.216.140';
const WS_IP = process.env.WS_IP;
const WS_PORT = 8091;
const WS_URI = 'im';
//心跳时间30s
const HEART_BEAT_TIMEOUT = 30000;
//signal
const CONNECT = 'CONNECT';
const DISCONNECT = 'DISCONNECT';
const CONNECT_ACK = 'CONNECT_ACK';
const PUBLISH_PRIVATE = 'PUBLISH_PRIVATE';
const GET_HIS_MSG = 'GET_HIS_MSG';
const PUBLISH_FRIEND = 'PUBLISH_FRIEND';
const FLUSH_CONVERSION = 'FLUSH_CONVERSION';
const NOTIFICATION = 'NOTIFICATION';


const NOTIFICATION_MESSAGE_ADD_FRIEND = "addFriends";
const PING = 'PING';

const DEFAULT_UPLOAD_IMG = "assets/img/default-text.png";

const DEFAULT_IMG_URL_PREFIX = "http://39.99.129.88:8808/avator";
export default {
  WS_PROTOCOL,
  WS_IP,
  WS_PORT,
  WS_URI,
  CONNECT,
  DISCONNECT,
  CONNECT_ACK,
  PUBLISH_PRIVATE,
  GET_HIS_MSG,
  FLUSH_CONVERSION,
  PING,
  PUBLISH_FRIEND,
  HEART_BEAT_TIMEOUT,
  DEFAULT_UPLOAD_IMG,
  DEFAULT_IMG_URL_PREFIX,
  NOTIFICATION_MESSAGE_ADD_FRIEND,
  NOTIFICATION
}
